version: '3.8'
services:
  krakend:
    image: krakend:latest
    platform: linux/amd64
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
      - ./plugins:/etc/krakend/plugins
    ports:
      - "8081:8080"
    environment:
      - WEATHERXM_API_KEY=${WEATHERXM_API_KEY}
      - X402_FACILITATOR_URL=${X402_FACILITATOR_URL:-http://host.docker.internal:8080}
      - PAYMENT_ADDRESS=${PAYMENT_ADDRESS}
      - MAX_AMOUNT_REQUIRED=${MAX_AMOUNT_REQUIRED:-1000000}
      - NETWORK=${NETWORK:-filecoin-calibration}
      - ASSET_ADDRESS=${ASSET_ADDRESS:-0xCD928583440157eDfB744201cb69dEeBDEe62bb8}
      - MAX_TIMEOUT_SECONDS=${MAX_TIMEOUT_SECONDS:-300}
    extra_hosts:
      - "host.docker.internal:host-gateway"